/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "Tether"
val prefix = rootProject.name.lowercase()
sequenceOf(
    "entities"
).forEach {
    include(it)
    project(":$it").name = "$prefix-$it"
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            // testing frameworks (see tether-java convention)
            version("mockito", "5.13.0")
            library("mockito-core", "org.mockito", "mockito-core").versionRef("mockito")
            library("mockito-junit-jupiter", "org.mockito", "mockito-junit-jupiter").versionRef("mockito")
            bundle("mockito", listOf("mockito-core", "mockito-junit-jupiter"))
        }
    }
}
