/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "Tether"

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            // annotations: https://central.sonatype.com/artifact/org.jetbrains/annotations
            library("jetbrains.annotations", "org.jetbrains:annotations:25.0.0")
        }
    }
}
